name: 'Pyright'

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pyright

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - uses: jakebailey/pyright-action@main
        with:
          version: '1.1.311' # renovate: datasource=npm depName=pyright
