name: 'Pyright'

on:
  workflow_dispatch

env:
  # renovate: datasource=npm depName=pyright
  PYRIGHT_VERSION: '1.1.311'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pyright

    steps:
      - uses: actions/checkout@v2

      - uses: jakebailey/pyright-action@03ab3c98073356eb56161009632b39fc2666321b # v2
        with:
          version: ${{ env.PYRIGHT_VERSION }}
